
package lt.eif.viko.amiliauskis.xslt.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-23T13:22:48.657+03:00
 * Generated source version: 3.4.3
 *
 */
public final class SolarSystemService_SolarSystemServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.xslt.amiliauskis.viko.eif.lt/", "SolarSystemServiceImplService");

    private SolarSystemService_SolarSystemServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SolarSystemServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SolarSystemServiceImplService ss = new SolarSystemServiceImplService(wsdlURL, SERVICE_NAME);
        SolarSystemService port = ss.getSolarSystemServiceImplPort();

        
        {
        System.out.println("Invoking addNewOutPlanet...");
        java.lang.String _addNewOutPlanet_arg0 = "Pluto";
        java.lang.Double _addNewOutPlanet_arg1 = 0.023;
        java.lang.String _addNewOutPlanet_arg2 = "Earths";
        java.lang.Double _addNewOutPlanet_arg3 = 0.027;
        java.lang.Integer _addNewOutPlanet_arg4 = 37;
        java.lang.String _addNewOutPlanet_arg5 = "km/s";
        java.lang.String _addNewOutPlanet_arg6 = "Terrestrial";
        lt.eif.viko.amiliauskis.xslt.soap.SolarSystem _addNewOutPlanet__return = port.addNewOutPlanet(_addNewOutPlanet_arg0, _addNewOutPlanet_arg1, _addNewOutPlanet_arg2, _addNewOutPlanet_arg3, _addNewOutPlanet_arg4, _addNewOutPlanet_arg5, _addNewOutPlanet_arg6);
        System.out.println("addNewOutPlanet.result=" + _addNewOutPlanet__return);


        }
        {
        System.out.println("Invoking deletePlanet...");
        java.lang.String _deletePlanet_arg0 = "Pluto";
        lt.eif.viko.amiliauskis.xslt.soap.SolarSystem _deletePlanet__return = port.deletePlanet(_deletePlanet_arg0);
        System.out.println("deletePlanet.result=" + _deletePlanet__return);


        }
        {
        System.out.println("Invoking addNewStar...");
        java.lang.String _addNewStar_arg0 = "SecondSun";
        java.lang.Integer _addNewStar_arg1 = 332012;
        java.lang.String _addNewStar_arg2 = "Earths";
        java.lang.Integer _addNewStar_arg3 = 134515;
        java.lang.Integer _addNewStar_arg4 = 513;
        java.lang.String _addNewStar_arg5 = "km/s";
        java.lang.Long _addNewStar_arg6 = 4600000000L;
        lt.eif.viko.amiliauskis.xslt.soap.SolarSystem _addNewStar__return = port.addNewStar(_addNewStar_arg0, _addNewStar_arg1, _addNewStar_arg2, _addNewStar_arg3, _addNewStar_arg4, _addNewStar_arg5, _addNewStar_arg6);
        System.out.println("addNewStar.result=" + _addNewStar__return);


        }
        
        {
        System.out.println("Invoking deleteAStar...");
        java.lang.String _deleteAStar_arg0 = "SecondSun";
        lt.eif.viko.amiliauskis.xslt.soap.SolarSystem _deleteAStar__return = port.deleteAStar(_deleteAStar_arg0);
        System.out.println("deleteAStar.result=" + _deleteAStar__return);


        }
        {
        System.out.println("Invoking getSolarSystem...");
        lt.eif.viko.amiliauskis.xslt.soap.SolarSystem _getSolarSystem__return = port.getSolarSystem();
        System.out.println("getSolarSystem.result=" + _getSolarSystem__return);


        }
        {
        System.out.println("Invoking addNewInnPlanet...");
        java.lang.String _addNewInnPlanet_arg0 = "Pluto";
        java.lang.Double _addNewInnPlanet_arg1 = 0.023;
        java.lang.String _addNewInnPlanet_arg2 = "Earths";
        java.lang.Double _addNewInnPlanet_arg3 = 0.027;
        java.lang.Integer _addNewInnPlanet_arg4 = 37;
        java.lang.String _addNewInnPlanet_arg5 = "km/s";
        java.lang.String _addNewInnPlanet_arg6 = "Terrestrial";
        lt.eif.viko.amiliauskis.xslt.soap.SolarSystem _addNewInnPlanet__return = port.addNewInnPlanet(_addNewInnPlanet_arg0, _addNewInnPlanet_arg1, _addNewInnPlanet_arg2, _addNewInnPlanet_arg3, _addNewInnPlanet_arg4, _addNewInnPlanet_arg5, _addNewInnPlanet_arg6);
        System.out.println("addNewInnPlanet.result=" + _addNewInnPlanet__return);


        }

        System.exit(0);
    }

}
