package lt.eif.viko.amiliauskis.xslt.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-23T13:22:48.702+03:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", name = "SolarSystemService")
@XmlSeeAlso({ObjectFactory.class})
public interface SolarSystemService {

    @WebMethod
    @Action(input = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/deleteAStarRequest", output = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/deleteAStarResponse")
    @RequestWrapper(localName = "deleteAStar", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.DeleteAStar")
    @ResponseWrapper(localName = "deleteAStarResponse", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.DeleteAStarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lt.eif.viko.amiliauskis.xslt.soap.SolarSystem deleteAStar(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/addNewOutPlanetRequest", output = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/addNewOutPlanetResponse")
    @RequestWrapper(localName = "addNewOutPlanet", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.AddNewOutPlanet")
    @ResponseWrapper(localName = "addNewOutPlanetResponse", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.AddNewOutPlanetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lt.eif.viko.amiliauskis.xslt.soap.SolarSystem addNewOutPlanet(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.Integer arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebMethod
    @Action(input = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/deletePlanetRequest", output = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/deletePlanetResponse")
    @RequestWrapper(localName = "deletePlanet", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.DeletePlanet")
    @ResponseWrapper(localName = "deletePlanetResponse", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.DeletePlanetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lt.eif.viko.amiliauskis.xslt.soap.SolarSystem deletePlanet(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/addNewStarRequest", output = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/addNewStarResponse")
    @RequestWrapper(localName = "addNewStar", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.AddNewStar")
    @ResponseWrapper(localName = "addNewStarResponse", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.AddNewStarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lt.eif.viko.amiliauskis.xslt.soap.SolarSystem addNewStar(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.Integer arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.Long arg6
    );

    @WebMethod
    @Action(input = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/getSolarSystemRequest", output = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/getSolarSystemResponse")
    @RequestWrapper(localName = "getSolarSystem", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.GetSolarSystem")
    @ResponseWrapper(localName = "getSolarSystemResponse", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.GetSolarSystemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lt.eif.viko.amiliauskis.xslt.soap.SolarSystem getSolarSystem()
;

    @WebMethod
    @Action(input = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/addNewInnPlanetRequest", output = "http://soap.xslt.amiliauskis.viko.eif.lt/SolarSystemService/addNewInnPlanetResponse")
    @RequestWrapper(localName = "addNewInnPlanet", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.AddNewInnPlanet")
    @ResponseWrapper(localName = "addNewInnPlanetResponse", targetNamespace = "http://soap.xslt.amiliauskis.viko.eif.lt/", className = "lt.eif.viko.amiliauskis.xslt.soap.AddNewInnPlanetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public lt.eif.viko.amiliauskis.xslt.soap.SolarSystem addNewInnPlanet(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.Integer arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );
}
