
package lt.eif.viko.amiliauskis.xslt.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-23T13:22:48.711+03:00
 * Generated source version: 3.4.3
 *
 */

public class SolarSystemService_SolarSystemServiceImplPort_Server{

    protected SolarSystemService_SolarSystemServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SolarSystemServiceImplPortImpl();
        String address = "http://localhost:5045/SolarSystemService/Transform";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new SolarSystemService_SolarSystemServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
